# Generated by Django 3.1.1 on 2020-09-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=33)),
                ('password', models.CharField(default=None, max_length=233)),
                ('mail', models.CharField(default=None, max_length=50)),
                ('student_id', models.IntegerField(default=0)),
                ('authority', models.CharField(default=None, max_length=23)),
                ('active', models.IntegerField(default=0)),
                ('rand_str', models.CharField(default=None, max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=233)),
                ('time', models.IntegerField(default=0)),
                ('content', models.CharField(default=None, max_length=2333)),
                ('user', models.CharField(default=None, max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='MySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(default=None, max_length=233)),
                ('username', models.CharField(default=None, max_length=33)),
            ],
        ),
    ]
